<div class="card card-login mx-auto mt-5">
    <div class="card-header">Login</div>
    <div class="card-body">
        <form method="post" action="<?php echo RUTA_URL . 'inicio/setlogin'; ?>">
            <center>
            <img src="<?php echo COMMON; ?>img/login.png">
            </center>
            <div class="form-group">
                <label for="exampleInputEmail1">Usuario</label>
                <?php if(isset($_COOKIE['user']) && !empty($_COOKIE['user'])){ ?>
                <input name="txtUsuario" value="<?php echo $_COOKIE['user']; ?>" class="form-control" id="exampleInputEmail1" required type="text" aria-describedby="emailHelp" placeholder="Ingrese usuario o correo">
                <?php }else{ ?>
                <input name="txtUsuario" required class="form-control" id="exampleInputEmail1" type="text" aria-describedby="emailHelp" placeholder="Ingrese usuario">
                <?php } ?>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Contraseña</label>
                <?php if(isset($_COOKIE['pass']) && !empty($_COOKIE['pass'])){ ?>
                <input name="txtPassword" required value="<?php echo $_COOKIE['pass']; ?>" class="form-control" id="exampleInputPassword1" type="password" placeholder="Ingrese contraseña">
                <?php }else{ ?>
                <input name="txtPassword" required class="form-control" id="exampleInputPassword1" type="password" placeholder="Ingrese contraseña">
                <?php } ?>
            </div>
            <div class="form-group">
                <?php if (isset($_COOKIE['user']) && $_COOKIE['pass']) { ?>
                    <div class="form-check">
                        <label class="form-check-label">
                            <input checked value="A" name="txtRecordarme" class="form-check-input" type="checkbox"> Recordar Contraseña
                        </label>
                    </div>
                <?php } else { ?>
                    <div class="form-check">
                        <label class="form-check-label">
                            <input value="I" name="txtRecordarme" class="form-check-input" type="checkbox"> Recordar Contraseña
                        </label>
                    </div>
                <?php } ?>
            </div>
            <div class="form-group">
                ¡No tienes una cuenta! <a href="<?php echo RUTA_URL . 'inicio/registro'; ?>"> Registrate</a>
            </div>
            <input type="submit" value="Login" class="btn btn-primary btn-block">
        </form>
    </div>
</div>