<script src="https://cdn.jsdelivr.net/gh/atatanasov/gijgo@1.7.3/dist/combined/js/gijgo.min.js" type="text/javascript"></script><link href="https://cdn.jsdelivr.net/gh/atatanasov/gijgo@1.7.3/dist/combined/css/gijgo.min.css" rel="stylesheet" type="text/css" />
<form id="formdatos">
    <div class="row">        
        <div class="col">            
            <div class="input-group">                
                <div class="input-group-prepend">                    
                    <div class="input-group-text">
                        <i class="fa fa-search"></i>
                    </div>                
                </div>                
                <input type="text" name="q" value="" class="form-control" placeholder="Palabra clave">            
            </div>        
        </div>        
        <div class="col">            
            <div class="input-group">                
                <div class="input-group-prepend">                    
                    <div class="input-group-text">
                        <i class="fa fa-male"></i></div>                
                </div>                
                <select name="pacient_id" class="form-control">                    
                    <option value="">PACIENTE</option>                    
                    <?php for ($i = 0; $i < count($this->usuarios); $i++) { ?>                        
                        <option value="<?php echo $this->usuarios[$i]['uiosEmailFK']; ?>"><?php echo $this->usuarios[$i]['uiosNombres']; ?></option>                    
                    <?php } ?>                
                </select>            
            </div>        
        </div>        
        <div class="col">            
            <div class="input-group">                
                <div class="input-group-prepend">                    
                    <div class="input-group-text"><i class="fa fa-support"></i>
                    </div>                
                </div>                
                <select name="medic_id" class="form-control">                    
                    <option value="">MEDICO</option>                    
                    <?php for ($i = 0; $i < count($this->medicos); $i++) { ?>                        
                        <option value="<?php echo $this->medicos[$i]['docId']; ?>"><?php echo $this->medicos[$i]['docNombre'] . ' ' . $this->medicos[$i]['docApellido']; ?></option>                    
                    <?php } ?>                
                </select>            
            </div>        
        </div>        
        <div class="col">            
            <div class="input-group">                
                <div class="input-group-prepend">                    
                    <div class="input-group-text"><i class="fa fa-calendar"></i>
                    </div>                
                </div>                
                <input type="date" class="form-control" name="date_at">            
            </div>        
        </div>        
        <div class="col">            
            <button class="btn btn-primary btn-block" type="button" id="btnBuscarDatos">Buscar</button>        
        </div>    
    </div>    
    <br/>    
    <input type="hidden" id="btnEstado" value="A">    
    <div id="vista">        
        <div class="card mb-3">            
            <div class="card-header">                
                <i class="fa fa-table"></i> Listado Citas
            </div>            
            <div class="card-body">                
                <div class="table-responsive">                    
                    <table class="table table-bordered" width="100%" cellspacing="0">                        
                        <thead>                            
                            <tr>                                
                                <th>Paciente</th>                                
                                <th>Asunto</th>                                
                                <th>Observaciones</th>                                
                                <th>Telefono</th>                                
                                <th>Fecha</th>                                
                                <th>Hora</th>                                
                                <th></th>                            
                            </tr>                        
                        </thead>                        
                        <tfoot>                            
                            <tr>                                
                                <th>Paciente</th>                                
                                <th>Asunto</th>                                
                                <th>Observaciones</th>                                
                                <th>Telefono</th>                                
                                <th>Fecha</th>                                
                                <th>Hora</th>                                
                                <th></th>                            
                            </tr>                        
                        </tfoot>                        
                        <tbody>                            
                            <?php for ($i = 0; $i < count($this->citas); $i++) { ?>  
                                <tr                                    
                                <?php if ($this->citas[$i]['ctasEstado'] == 'Pendiente') { ?> 
                                        class="table-warning"                                    
                                    <?php } else if ($this->citas[$i]['ctasEstado'] == 'Programada') { ?> 
                                        class="table-success"                                    
                                    <?php } else if ($this->citas[$i]['ctasEstado'] == 'Cancelada') { ?>                                        
                                        class="table-danger"                                    
                                    <?php } else { ?>
                                        class="table-info"
                                    <?php } ?>
                                    >                                    
                                    <td><?php echo ucwords(strtolower($this->citas[$i]['uiosNombres'])); ?></td> 
                                    <td><?php echo $this->citas[$i]['espNombre']; ?></td>     
                                    <td><?php echo $this->citas[$i]['ctasObservaciones']; ?></td>   
                                    <td><?php echo $this->citas[$i]['uiosTelefono']; ?></td>    
                                    <td><?php echo $this->citas[$i]['ctasFecha']; ?></td>    
                                    <td><?php echo $this->citas[$i]['ctasHora']; ?></td>  
                                    <?php if ($this->citas[$i]['ctasEstado'] == 'Pendiente') { ?> 
                                        <td class="text-center">
                                            <button type="button" id="btnProgramar" value="<?php echo $this->citas[$i]['ctasId']; ?>" class="btn btn-success"><i class="fa fa-fw fa-clock-o"></i>Programar</button>
                                        </td>                                    
                                    <?php } else if ($this->citas[$i]['ctasEstado'] == 'Programada') { ?> 
                                        <td class="text-center">
                                            <button type="button" id="btnProgramar" value="<?php echo $this->citas[$i]['ctasId']; ?>" class="btn btn-warning"><i class="fa fa-fw fa-clock-o"></i>Programada</button>
                                        </td>                                    
                                    <?php } else if ($this->citas[$i]['ctasEstado'] == 'Cancelada') { ?>   
                                        <td class="text-center">
                                            <button type="button" class="btn btn-danger"><i class="fa fa-fw fa-window-close"></i>Cancelada</button>
                                        </td>                                    
                                    <?php } else { ?>
                                        <td class="text-center">
                                            <button type="button" class="btn btn-primary"><i class="fa fa-fw fa-check"></i>Atendida</button>
                                        </td> 
                                    <?php } ?>                                
                                </tr>                            
                            <?php } ?>                       
                        </tbody>                    
                    </table>                
                </div>            
            </div>        
        </div>    
    </div>    
    <div class="modal modal fade" id="ProgramarModal" tabindex="-1" role="dialog">        
        <div class="modal-dialog" role="document">            
            <div class="modal-content">                
                <div class="modal-header">                    
                    <h5 class="modal-title" id="exampleModalLabel">Programar Citas</h5>   
                    <button class="close" type="button" id="btnCerrarModal" data-dismiss="modal" aria-label="Close">   
                        <span aria-hidden="true">×</span> 
                    </button>                
                </div>                
                <div class="modal-body" id="contenidoModal"></div>  
                <div class="modal-footer">                    
                    <button class="btn btn-default d-none" type="button" id="btnCancelarCita">Cancelar Cita</button> 
                    <button class="btn btn-success" id='btnGuardar' type="button">Guardar</button>
                    <button class="btn btn-danger" type="button" id="btnCerrarModal" data-dismiss="modal">Cerrar</button> 
                </div>            
            </div>        
        </div>    
    </div>    
    <script>
        $('.datepicker').datepicker({
            uiLibrary: 'bootstrap4',
            format: 'yyyy/mm/dd'});
    </script>