<div id="vistaCitas">
    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-table"></i> Citas Asignadas</div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="dataTable" class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Paciente</th>
                            <th>Asunto</th>
                            <th>Observaciones</th>
                            <th>Telefono</th>
                            <th>Fecha</th>
                            <th>Hora</th>
                            <th>Sede</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Paciente</th>
                            <th>Asunto</th>
                            <th>Observaciones</th>
                            <th>Telefono</th>
                            <th>Fecha</th>
                            <th>Hora</th>
                            <th>Sede</th>
                            <th></th>
                        </tr>
                    </tfoot>
                    <tbody>
                        <?php for ($i = 0; $i < count($this->citas); $i++) { ?>
                            <tr>
                                <td><?php echo ucwords(strtolower($this->citas[$i]['uiosNombres'])); ?></td>
                                <td><?php echo $this->citas[$i]['espNombre']; ?></td>
                                <td><?php echo $this->citas[$i]['ctasObservaciones']; ?></td>
                                <td><?php echo $this->citas[$i]['uiosTelefono']; ?></td>
                                <td><?php echo $this->citas[$i]['pdoFecha']; ?></td>
                                <td><?php echo $this->citas[$i]['pdoHora']; ?></td>
                                <td><?php echo $this->citas[$i]['sedeNombre']; ?></td>
                                <td class="text-center">
                                    <?php if($this->citas[$i]['ctasEstado']=='Programada'){ ?>
                                    <button id="btnAtender" value="<?php echo $this->citas[$i]['ctasId']; ?>" class="btn btn-success"><i class="fa fa-user-md" aria-hidden="true"></i></button>
                                    <?php } ?>
                                    <button id="btnHistoriaClinica" value="<?php echo $this->citas[$i]['ctasId']; ?>" class="btn btn-primary"><i class="fa fa-h-square" aria-hidden="true"></i></button>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
