<div class="card card-register mx-auto mt-5">
    <div class="card-header">Por favor trate de que los archivos no contengan caracteres especiales (tildes, comas, ñ etc)</div>
    <div class="card-body">
        <div class="form-group">
            <div class="form-row">
                <div class="col-md-6">
                    <label>Seleccione Certificado</label>
                </div>
                <div class="col-md-6">
                    <input type="file" name="txtCertificado[]">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label>Presion este boton para subir otros documentos</label>
            <div class="text-center">
                <button type="button" class="btn btn-danger" id="btnOtros">Otros</button>
            </div>
        </div>
        <div id="otrosArchivos"></div>
    </div>
</div>


