<div class="card card-register mx-auto mt-5">
    <div class="card-header"><?php echo $this->accion; ?></div>
    <div class="card-body">
        <form method="post" action="<?php echo RUTA_URL . 'administracion/setespe'; ?>">
            <input type="hidden" name="txtCodigo" value="<?php if(empty($this->datos)){}else{ echo $this->datos[0]['espId'];} ?>">
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <label for="exampleInputName">Especialidad</label>
                        <input name="txtNombre" class="form-control" value="<?php if(empty($this->datos)){}else{  echo $this->datos[0]['espNombre'];} ?>" id="exampleInputName" type="text" aria-describedby="nameHelp" placeholder="Ingrese nombre">
                    </div>
                    <div class="col-md-6">
                </div>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Descripcion</label>
                <textarea class="form-control" placeholder="Descripcion especialidad (que hace)" name="txtDescripcion"><?php if(empty($this->datos)){}else{ echo $this->datos[0]['espDescripcion']; }?></textarea>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <input type="submit" class="btn btn-success btn-block" value="Guardar">
                    </div>
                    <div class="col-md-6">
                        <a class="btn btn-danger btn-block" href="<?php echo RUTA_URL . 'administracion/especialidades'; ?>">Volver</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>



