<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Pqrsf
    </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Usuario</th>
                        <th>Correo</th>
                        <th>Telefono</th>
                        <th>Tipo</th>
                        <th>Descripcion</th>
                        <th>Fecha</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Usuario</th>
                        <th>Correo</th>
                        <th>Telefono</th>
                        <th>Tipo</th>
                        <th>Descripcion</th>
                        <th>Fecha</th>
                    </tr>
                </tfoot>
                <tbody>
                    <?php for ($i = 0; $i < count($this->pqrsf); $i++) { ?>
                        <tr>
                            <td><?php echo ucwords(strtolower($this->pqrsf[$i]['uiosNombres'])); ?></td>
                            <td><?php echo $this->pqrsf[$i]['psfCorreo']; ?></td>
                            <td><?php echo $this->pqrsf[$i]['uiosTelefono']; ?></td>
                            <td><?php echo $this->pqrsf[$i]['psfTipo']; ?></td>
                            <td><?php echo $this->pqrsf[$i]['psfDescripcion']; ?></td>
                            <td><?php echo $this->pqrsf[$i]['psfFecha']; ?></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
            </div>
        </div>
</div>