<div id="vista">
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Administracion Usuarios</div>
    <div class="card-body">
        <button class="btn btn-success" style="margin-bottom: 9px;" id="btnAgregarRoles">Agregar</button>
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Rol</th>
                        <th></th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Nombre</th>
                        <th>Rol</th>
                        <th></th>
                    </tr>
                </tfoot>
                <tbody>
                    <?php for ($i = 0; $i < count($this->usuarios); $i++) { ?>
                        <tr>
                            <td><?php echo $this->usuarios[$i]['rlesNombreRol']; ?></td>
                            <td><?php echo $this->usuarios[$i]['rlesTipo']; ?></td>
                            <td class="text-center">
                                <button value="<?php echo $this->usuarios[$i]['rlesId']; ?>" class="btn btn-warning" id="btnEditarRoles"><i class="fa fa-pencil-square-o"></i></button>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>      
    </div>
</div>
</div>
