<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Usuarios</div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Correo</th>
                        <th>Documento</th>
                        <th>Telefono</th>
                        <th>Fecha Nacimiento</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Nombre</th>
                        <th>Correo</th>
                        <th>Documento</th>
                        <th>Telefono</th>
                        <th>Fecha Nacimiento</th>
                    </tr>
                </tfoot>
                <tbody>
                    <?php for ($i = 0; $i < count($this->usuarios); $i++) { ?>
                        <tr>
                            <td><?php echo ucwords(strtolower($this->usuarios[$i]['uiosNombres'])); ?></td>
                            <td><?php echo $this->usuarios[$i]['uiosEmailFK']; ?></td>
                            <td><?php echo $this->usuarios[$i]['uiosDocumento']; ?></td>
                            <td><?php echo $this->usuarios[$i]['uiosTelefono']; ?></td>
                            <td><?php echo $this->usuarios[$i]['uiosFechaEspecial']; ?></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

