<div class="card card-register mx-auto mt-5">
    <div class="card-header">Editar informacion</div>
    <div class="card-body">
        <div class="form-group">
            <div class="form-row">
                <div class="col-md-6">
                    <label>Digite contraseña actual</label>
                </div>
                <div class="col-md-6">
                    <input type="password" class="form-control" id="txtPassword" placeholder="Contraseña">
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="text-center">
                <button class="btn btn-primary" id="btnEnviar">Enviar</button>
            </div>
        </div>
    </div>
</div>
<div id="formularioEditar"></div>
