<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Listado Citas</div>
    <div class="card-body">
        <div class="table-responsive">
            <table id="dataTable" class="table table-bordered" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Paciente</th>
                        <th>Asunto</th>
                        <th>Observaciones</th>
                        <th>Telefono</th>
                        <th>Fecha</th>
                        <th>Hora</th>
                        <th></th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Paciente</th>
                        <th>Asunto</th>
                        <th>Observaciones</th>
                        <th>Telefono</th>
                        <th>Fecha</th>
                        <th>Hora</th>
                        <th></th>
                    </tr>
                </tfoot>
                <tbody>
                    <?php for ($i = 0; $i < count($this->citas); $i++) { ?>
                        <tr
                        <?php if ($this->citas[$i]['ctasEstado'] == 'Pendiente') { ?>
                                class="table-warning"
                            <?php } else if ($this->citas[$i]['ctasEstado'] == 'Programada') { ?>
                                class="table-success"
                            <?php } else if ($this->citas[$i]['ctasEstado'] == 'Cancelada') { ?>
                                class="table-danger"
                            <?php } else { ?>
                                class="table-info"
                            <?php } ?>
                            >
                            <td><?php echo ucwords(strtolower($this->citas[$i]['uiosNombres'])); ?></td>
                            <td><?php echo $this->citas[$i]['espNombre']; ?></td>
                            <td><?php echo $this->citas[$i]['ctasObservaciones']; ?></td>
                            <td><?php echo $this->citas[$i]['uiosTelefono']; ?></td>
                            <td><?php echo $this->citas[$i]['ctasFecha']; ?></td>
                            <td><?php echo $this->citas[$i]['ctasHora']; ?></td>
                            <?php if ($this->citas[$i]['ctasEstado'] == 'Pendiente') { ?>
                                <td class="text-center"><button type="button" class="btn btn-success"><i class="fa fa-fw fa-clock-o"></i>Pendiente</button></td>
                            <?php } else if ($this->citas[$i]['ctasEstado'] == 'Programada') { ?>
                                <td class="text-center"><button type="button" id="btnVerProgramar" value="<?php echo $this->citas[$i]['ctasId']; ?>" class="btn btn-warning"><i class="fa fa-fw fa-clock-o"></i>Programada</button></td>
                            <?php } else if ($this->citas[$i]['ctasEstado'] == 'Cancelada') { ?>
                                <td class="text-center"><button type="button" class="btn btn-danger"><i class="fa fa-fw fa-window-close"></i>Cancelada</button></td>
                            <?php } else { ?>
                                <td class="text-center"><button type="button" class="btn btn-primary"><i class="fa fa-fw fa-check"></i>Atendida</button></td>
                            <?php } ?>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal modal fade" id="CitasModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Informacio Cita</h5>
                <button class="close" type="button" id="btnCerrarModal" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" id="contenidoModal"></div>
            <div class="modal-footer">
                <button class="btn btn-danger" type="button" id="btnCerrarModal" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
