<?php
date_default_timezone_set('America/Bogota');
?>
<div class="card card-register mx-auto mt-5">
    <div class="card-header">Solicitar cita</div>
    <div class="card-body">
        <form id="form1" method="post" action="<?php echo RUTA_URL . 'usuario/nuevacita'; ?>">
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-8">
                        <label for="exampleInputName">Nombre</label>
                        <input disabled value="<?php echo $this->datos[0]['uiosNombres']; ?>" name="txtNombre" class="form-control" id="exampleInputName" type="text" aria-describedby="nameHelp" placeholder="Ingrese nombre">
                    </div>
                    <div class="col-md-4">

                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <label for="exampleInputEmail1">Documento</label>
                        <input disabled value="<?php echo $this->datos[0]['uiosDocumento']; ?>" name="txtDocumento" class="form-control" id="exampleInputDocu" type="text" aria-describedby="AdressHelp" placeholder="Ingrese documento">
                    </div>
                    <div class="col-md-6">
                        <label for="exampleInputEmail1">Telefono</label>
                        <input disabled value="<?php echo $this->datos[0]['uiosTelefono']; ?>" name="txtTelefono" class="form-control" id="exampleInputTelefono" type="number" aria-describedby="AdressHelp" placeholder="Ingrese telefono">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <label for="exampleInputPassword1">Correo electronico</label>
                        <input disabled value="<?php echo $this->datos[0]['uiosEmailFK']; ?>" name="txtCorreo" class="form-control" id="exampleInputEmail" type="email" placeholder="ingrese correo">
                    </div>
                    <div class="col-md-6">
                        <label  for="exampleConfirmPassword">Fecha de nacimiento</label>
                        <input disabled value="<?php echo $this->datos[0]['uiosFechaEspecial']; ?>" name="txtFecha" class="form-control" id="exampleInputFecha" type="date">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <label for="exampleInputPassword1">Fecha</label>
                        <input disabled value="<?php echo date('Y-m-d'); ?>" class="form-control" id="exampleInputFechaA" type="text">
                    </div>
                    <div class="col-md-6">
                        <label  for="exampleConfirmPassword">Hora</label>
                        <input disabled value="<?php echo date('H:i:s'); ?>" class="form-control" id="exampleInputHoraA" type="text">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-8">
                        <label for="exampleInputPassword1">Especialidad</label>
                        <select name="txtEspecialidad" class="form-control">
                            <option disabled selected>--Seleccione--</option>
                            <?php for ($i = 0; $i < count($this->especialidad); $i++) { ?>
                                <option value="<?php echo $this->especialidad[$i]['espId']; ?>"><?php echo $this->especialidad[$i]['espNombre']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="col-md-4">

                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Motivo de consulta</label>
                <textarea name="txtMotivo" class="form-control" placeholder="Ingrese motivo de consulta"></textarea>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <input type="submit" class="btn btn-success btn-block" value="Guardar">
                    </div>
                    <div class="col-md-6">
                        <button class="btn btn-primary btn-block" type="reset">Limpiar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    function mostrarhora() {
        var hora = new Date();
        var horaA = hora.getHours() + ":" + hora.getMinutes() + ":" + hora.getSeconds();
        $('#exampleInputHoraA').val(horaA);
    }
    setInterval("mostrarhora()", 1000);
</script>
