<?php if (Session::get('autenticado')) { ?>
    </div>
    </div>
    <footer class="sticky-footer">
        <div class="container">
            <div class="text-center">
                <small>Copyright © 2020 - Integracion Continua</small>
            </div>
        </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fa fa-angle-up"></i>
    </a>
<?php } ?>
<script src="<?php echo COMMON; ?>js/ajax.js"></script>
<script src="<?php echo COMMON; ?>js/pnotify.custom.min.js"></script>
<script src="<?php echo $_layoutParams['ruta_js']; ?>script.js" type="text/javascript"></script>
<script src="<?php echo COMMON; ?>vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="<?php echo COMMON; ?>vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="<?php echo COMMON; ?>vendor/datatables/jquery.dataTables.js"></script>
<script src="<?php echo COMMON; ?>vendor/datatables/dataTables.bootstrap4.js"></script>
<script src="<?php echo COMMON; ?>js/sb-admin.min.js"></script>
<script src="<?php echo COMMON; ?>js/sb-admin-datatables.min.js"></script>
<?php echo LIB_VALIDATOR; ?>
<script src='<?php echo COMMON; ?>js/validar.js'></script>
</div>
</body>
</html>
